blank_issues_enabled: false

contact_links:

  - name: 'â„¹ï¸â€‚ '
    about: Please ask and answer questions here.
    url: https://github.com/orgs/community/discussions

  - name: 'â‰ï¸â€‚ '
    about: Please ask and answer questions here.
    url: https://github.com/orgs/community/discussions

  - name: 'ğŸ“®GitHub Security Bug Bounty'
    about: Please report security vulnerabilities here.
    url: https://bounty.github.com/

