blank_issues_enabled: false

contact_links:

  - name: 'ğŸ“ï¸â€‚ Learn More'
    about: Not sure where to start? Read our contributing guide to learn more.
    url: https://github.com/orgs/community/discussions

  - name: 'ğŸ’¬â€‚ Contact Us'
    about:  Have another inquiry or need help? Contact us directly!
    url: https://bounty.github.com/
