blank_issues_enabled: false
contact_links:
- name: ğŸ“ï¸â€‚ Learn More
  about: Not sure where to start? Read our contributing guide to learn more.
  url: https://github.com/AAriam/TemplateRepo/blob/main/CONTRIBUTING.md
- name: ğŸ’¬â€‚ Contact Us
  about: Have another inquiry or need help? Contact us directly!
  url: https://aariam.github.io/TemplateRepo/help/contact
