# Build the documentation with Sphinx and upload the builds as artifacts.

name: 'Docs - Build'
run-name: 'Docs: Build from ${{github.ref}}'

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: micromamba-shell {0}


jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup environment'
        # https://github.com/mamba-org/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: docs/website_sphinx/requirements.yaml
          generate-run-shell: true
          init-shell: bash

      # To make PDF output, we need the latexmk package and some other plugins, which are not available via conda.
      - name: 'Install extra requirements'
        if: always()
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra tex-gyre

      - name: 'Install package'
        if: always()
        run: python -m pip install .

      - name: 'Display conda environment'
        if: always()
        shell: bash -el {0}
        run: micromamba list

      - name: 'Display pip environment'
        if: always()
        run: pip list

      - name: 'Display non-Python packages'
        if: always()
        run: |
          echo "latexmk Version:"
          latexmk --version
          echo "rsvg Version:"
          rsvg-convert --version

      - name: 'Display directory tree'
        if: always()
        shell: bash -el {0}
        run: ls -a

      - name: 'Build HTML'
        if: always()
        run: |
          cd docs/website_sphinx
          make clean
          make dirhtml

      - name: 'Build LaTeX'
        if: always()
        # Use `make latex` instead of `make latexpdf` to be able to pass extra arguments to `latexmk` in next step.
        run: |
          cd docs/website_sphinx
          make latex

      - name: 'Build PDF'
        if: always()
        # latexmk docs: https://ctan.mc1.root.project-creative.net/support/latexmk/latexmk.pdf
        run : |
          cd docs/website_sphinx/_build/latex
          LATEXMKOPTS="-outdir=./pdf -auxdir=./aux -bibfudge- -makeindexfudge-" make 

      - name: 'Display builds'
        if: always()
        run: find docs/website_sphinx/_build

      - name: 'Order builds'
        if: always()
        run : |
          mv docs/website_sphinx/_build/dirhtml docs/website_sphinx/_build/html
          mkdir -p docs/website_sphinx/_build/pdf/log
          mv docs/website_sphinx/_build/latex/aux docs/website_sphinx/_build/pdf
          mv docs/website_sphinx/_build/latex/pdf/* docs/website_sphinx/_build/pdf/log
          mv docs/website_sphinx/_build/pdf/log/*.pdf docs/website_sphinx/_build/pdf

      - name: 'Display ordered builds'
        if: always()
        run: find docs/website_sphinx/_build

      - name: 'Upload builds'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: docs/website_sphinx/_build/*
          name: 'docs'

      - name: 'Upload GitHub Pages artifact'
        # https://github.com/actions/upload-pages-artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/website_sphinx/_build/html'
