# Deploy the documentation to GitHub Pages.

name: 'Docs - GH Pages'
run-name: 'Docs: Deploy to GitHub Pages from ${{github.ref_name}}'

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact-name:
        description: >-
          Name of the artifact containing the HTML files. 
          This artifact must have been created in the caller workflow 
          before running this workflow.
        default: 'Docs - HTML Build (GH Pages)'
        required: false
        type: string


jobs:

  deploy:
    # Ref: https://github.com/actions/starter-workflows/blob/main/pages/static.yml
    # Ref: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
    name: 'Deploy to GitHub Pages'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup GitHub Pages'
        # https://github.com/actions/configure-pages
        uses: actions/configure-pages@v3
        with:
          enablement: true

      - name: 'Download gh-pages artifact'
        uses: actions/download-artifact@v3
        with:
          name: github-pages

      - name: 'Display file tree'
        run: find .

      - name: 'Deploy'
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v2

